version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "3211:${PGPORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - './src/shared/infra/postgres/initdb:/docker-entrypoint-initdb.d'

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - './src/shared/infra/mongo/initdb:/docker-entrypoint-initdb.d/mongo'


  buzzy_paint_app:
    build:
      context: .
      args:
        PGUSER: ${PGUSER}
        PGPASSWORD: ${PGPASSWORD}
        PGHOST: ${PGHOST}
        PGPORT: ${PGPORT}
        PGDATABASE: ${PGDATABASE}
        MONGO_ROOT_USER: ${MONGO_ROOT_USER}
        MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        PORT: ${PORT}
    container_name: deno_app
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      MONGO_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      PORT: ${PORT}
    depends_on:
      - postgres
      - mongo

volumes:
  postgres_data:
  mongo_data:
